module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Starbucks',
    'McDonalds',
    'Nordstrom Rack',
    'Target',
    'Walmart',
    'Costco',
    'Chevron',
    'Shell',
    'Taco Bell',
    'Chiptole',
    'Rest Stop',
    'Barnes and Noble',
    'Jollibee',
    'Westfield mall',
    'Old Navy',
    'Pho Bahn Mai',
    'Tea Station',
    'Convoy Music Bar',
    'Jack in the Box',
    'Subway',
    "Ike's Sandwiches"
]
